name: vless-app
services:
- name: v2ray
  source_dir: /
  github:
    repo: karyan6/ttakfree
    branch: main
  run_command: v2ray run -config /etc/v2ray/config.json
  build_command: echo "No build needed"
  environment_slug: docker
  dockerfile_path: Dockerfile
  instance_size_slug: basic-xxs
  instance_count: 1
  routes:
  - path: /
  http_port: 8080
